apiVersion: v1
kind: Secret
metadata:
  name: springboot-todo-api-secrets
type: Opaque
stringData:
  POSTGRESQL_HOST: "<INSERT_SERVER_FQDN>"
  POSTGRESQL_USERNAME: "<INSERT_USERNAME>"
  # Not used for passwordless authentication
  # POSTGRESQL_PASSWORD: "<INSERT_PASSWORD>"
  APPLICATIONINSIGHTS_CONNECTION_STRING: "<INSERT_CONNECTION_STRING>"
